name: Train, Build and Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
      
      - name: Installing Requirements
        run: |
          pip install -r requirements.txt
      
      - name: Training the Model
        run: |
          python train_model.py
      
      - name: Building Docker Container
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-test-app:latest .
      
      - name: Login in To DockerHUB
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push to DockerHUB
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-test-app:latest