name: Train and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Installing the Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Traing the Model
        run: |
          python train_model.py
      
      - name: Building the docker container
        run: |
          docker build -t mlops-pract .
      